### ISSUE TITLE
Naming things within selectors spec consistently

### ISSUE THREAD

**Issue by vmx** [ipld/specs#103]
The [Selectors spec](https://github.com/ipld/specs/blob/master/selectors/selectors.md) has it's first draft, but there's still issues with naming things. During [review of the spec by @rvagg](https://github.com/ipld/specs/pull/95/files/7ba014c1b6868514eb461db3c3126136b9250bdc#r264505323), he e.g. brought up:

> There seems to be a linguistic disconnect here between 'path' and 'map', could it be brought in better alignment? `SelectMapAll` -> `SelectPathAll` or `SelectPath` -> `SelectKey`?

It is a good point. So we should think about if e.g. `PathSegment` is a good name, or if we should talk about `Keys` (or something else) here that form a `Path`.

**Comment by rvagg** [comment]
I noticed the use of "index" in @warpfork's docs to refer to a child of both an array and a map: https://github.com/ipld/go-ipld-prime/pull/3/files#diff-93ba0b52fd5157a2aef7910e9c0cf245R8
That could just be Go-speak but I quite like that as a generic way of referring to children of either of those types. It might be slightly confusing to JavaScript folks but they have the Array-can-be-a-map-too thing so it's not totally foreign.
