### ISSUE TITLE
Nested recursive traversal

### ISSUE THREAD

**Issue by vmx** [ipld/specs#106]
Quoting @Stebalien from https://github.com/ipld/specs/pull/95#discussion_r266758452:

> Let's say that I want to lookup a specific path on each block along a chain. I think we'll need a way to fork. Maybe something like:
> 
> ```
> {
>   "recursive": {
>     "follow": ...,
>     "select": ...,
>     "stop": ...,
>   }
> }
> ```

**Comment by Stebalien** [comment]
Sorry, I was unclear. I want to traverse:

```
block -> block -> block -> ...
  |        |        |
  v        v        v
thing    thing    thing
```

That is, I want to follow parent points down a chain, invoking a selector on each block's children.

**Comment by vmx** [comment]
Sounds like a recursive selector within a recursive selector. I had hoped we won't need this, but it looks like we do.
