### ISSUE TITLE
Too much detail for spec?

### ISSUE THREAD

**Issue by rvagg** [ipld/specs#127]
I want to create a new HashMap (HAMT) spec that leans on #109 but extends it with more formality about the algorithm, but as I get into it I'm concerned that it might be too much detail. I don't mind writing this, but maybe I'm either overestimating the interest & needs of the reader or underestimating the intelligence of the audience.

This is just for a `Set` (`Put`) operation. `Get` will be shorter but `Delete` will be larger. Can I get some feedback?

**`Set(key, value)`**

1. Set a `depth` value to `0`, indicating the root block
2. The `key` is hashed, using `hashAlg`.
3. Take the left-most `bitWidth` bits, offset by `depth x bitWidth`, from the hash to form an `index`. At each level of the data structure, we increment the section of bits we take from the hash so that the `index` comprises a different set of bits as we move down.
4. If the `index` bit in the node's `map` is `0`, a new bucket needs to be created at the current node. If the `index` bit in the node's `map` is `1`, a value exists for this `index` in the node's `data` which may be a bucket (which may be full) or may be a link to a child node.
5. A `popcount()` is performed on the `map` up to `index` such that we count the number of `1` bits up to the `index` bit-position. This gives us `dataIndex`, an index in the `data` array to look up the value or insert a new bucket.
6. If the `index` bit in the node's `map` is `0`:
   1. Mutate the current node (create a copy).
   2. Insert a new element in `data` at `dataIndex` containing an new bucket (array) with a single entry for the `key` / `value` pair.
   3. Create a CID for the mutated node.
   4. If `depth` is `0`, the CID represents the new root block of the HashMap.
   5. If `depth` is greater than `0`:
      1. Mutate the node's parent
      2. Record the new CID of the mutated child in the appropriate position of the mutated parent's `data` array. 
      3. Recursively proceed, by recording the new CIDs of each node in a mutated copy of its parent node until `depth` of `0` where we produce the the new root block and its CID.
7. If the `index` bit in the node's `map` is `1`:
   1. If the `dataIndex` element of `data` contains a link (CID) to a child block, increment `depth` and repeat with the child node identified by the link from step **3**.
   2. If the `dataIndex` element of `data` contains a bucket (array) and the bucket's size is less than `bucketSize`:
      1. Mutate the current node (create a copy).
      2. Insert the `key` / `value` pair into the new bucket at a position sorted by `key` such that all entries in the bucket are ordered respective to their `key`s. (This helps ensure canonical form.)
      3. Proceed to create new CIDs for the current block and each parent as per step 6.c. until we have a new root block and its CID.
   3. If the `dataIndex` element of `data` contains a bucket (array) and the bucket's size is `bucketSize`:
      1. Create a new empty node
      2. For each element of the bucket, perform a `Set(key, value)` on the new empty node with a `depth` set to `depth + 1`, proceeding from step 2. This should create a new node with `bucketSize` elements distributed approximately evenly through its `data` array. This operation will only result in more than one new node being created if all `key`s being set have the same `bitWidth` bits of their hashes at `bitWidth` position `depth + 1` (and so on). A sufficiently random hash algorithm should prevent this from occuring.
      3.  Create a CID for the new child node.
      4.  Mutate the current node (create a copy)
      5.  Replace `dataIndex` of `data` with a link to the new child node.
      6.  Proceed to create new CIDs for the current block and each parent as per step 6.c. until we have a new root block and its CID.

**Comment by warpfork** [comment]
I super like this.  I skimmed it even with a jetlagged tiredbrain last night, and it more or less made sense and gave me a general feeling of confidence I could grind this into code without too many questions.  "Could grind this into code without too many questions" is totally the level of detail I think we should shoot for.

One thing I'd appreciate in addition to this: a short header section that just lists out all the param names that are going to be in action.  E.g. I see `hashAlg`, `bitWidth`, `bucketSize`... is that it?

**Comment by rvagg** [comment]
great, I'll keep on in this way and see how it ends up when put together as a full spec

and ya, there's already some info on these undefined pieces in the lead-in:

-----

### Parameters

Configurable properties for any given HashMap:

 * `hashAlg`: The hash algorithm applied to keys in order to evenly distribute entries throughout the data structure. The algorithm may be chosen based on speed, byte-size and randomness properties.
 * `bitWidth`: The number of bits to use at each level of the data structure for determining the index of the entry or the a link to the next level of the data structure to continue searching. The equation 2<sup>`bitWidth`</sup> yields the arity of the HashMap nodes, i.e. the number of storage locations for buckets and/or links to child nodes.
 * `bucketSize`: The maximum array size of entry storage buckets such that exceeding `bucketSize` causes the creation of a new child node to replace entry storage.

### Node properties

Each node in a HashMap data structure contains:

 * `data`: An array, with a length of zero to 2<sup>`bitWidth`</sup>.
 * `map`: A bitmap where the first `bitWidth` bits are used to indicate whether a bucket or child node link is present at each possible index of the node.

An important property of a HAMT is that the `data` array only contains active elements. Indexes in a node that do not contain any values (in buckets or links to child nodes) are not stored and the `map` bitmap is used to determine the `data` whether values are present and the array index of present values using a `popcount()`.

**Comment by vmx** [comment]
Perhaps the spec could be brief, for those just wanting to get the idea. And then there could be an "implementation guide" which goes deeper into the algorithmic details which you would read if you want to implement it.

**Comment by rvagg** [comment]
I'm just finishing polishing my rather large spec document .. didn't PR it today because it has a couple of lose ends. If you don't like this level of detail then you're not going to like my doc ... It could be split up I suppose but maybe we can discuss that in the PR.

**Comment by rvagg** [comment]
OK, so I originally went with more of the kind of detail I went into above but then wrote a more plainly explained version of it in a summary. Hopefully I've hit a suitable middle ground. #131.
