### ISSUE TITLE
TODO: restore some kind of spec for CAR

### ISSUE THREAD

**Issue by rvagg** [ipld/specs#165]
As mentioned in https://github.com/ipld/specs/pull/69#issuecomment-521154614, CAR.md was removed in #72 but go-car is in active use by Filecoin so it probably deserves a spec. I'd also like to spec my ZIP CAR format too since I have active implementations that I'm using for IPLD tests and I reckon it will be useful for other purposes too.

So, this issue is both a TODO for me because I'd like to work on these specs but also a question regarding whether we want them in here? It's not clear to me why CAR.md was removed exactly but maybe there's a feeling that it doesn't belong here for some reason?

**Comment by ribasushi** [comment]
This was closed by https://github.com/ipld/specs/pull/230, don't have perms to close issue.
