### ISSUE TITLE
Advanced layout usage schema syntax decisions

### ISSUE THREAD

**Issue by rvagg** [ipld/specs#190]
See #182 (& #183 to a lesser degree) for background. Let's isolate the specific question of how you reference an advanced layout in your schemas.

Say we have an advanced layout called `ROT13`, defined simply with `advanced ROT13`. This advanced layout can be used in place of a string kind. How would you use it?

These are essentially fancy "representations", so my initial proposal was:

```
type MyString string representation ROT13
```

And you could parameterise this with curly brackets as per #183. This usage means that if you want to use `ROT13` a property of a struct or value of a map or list you'd have to first define it as a distinct type (`MyString`) and then use that type in those places:

```
type MyString string representation ROT13

type Foo struct {
  bar Int
  baz MyString
}
```

@warpfork has objections to just reusing the representation type position for this, see https://github.com/ipld/specs/pull/182#discussion_r318935284. We settled on a long-hand version that would also encode nicely to the schema-schema (and probably be easier in Go for typing reasons).

```
type MyString string representation advanced {
  name ROT13
}
```

Adding parameters as in #183 would mean add a `parameters` property inside here which is a simple map containing the parameters you're allowed to use for that representation.

But we're getting quite verbose now. Is that a problem?

There seems to be a yearning for a short-hand for these things, so what would that look like, and does it preclude the ability to also have a long-hand version (we've been opting for only having one-way of doing things as much as practical so far).

```
type Foo struct {
  bar Int
  baz MyString<ROT13>
}
```

As mentioned in https://github.com/ipld/specs/pull/182#issuecomment-526423763, I'm not a fan of `<>` because of its templating/generics use in prominent languages and that's not what we're doing here (it's the inverse).

If we must have a shorthand, maybe this?

```
baz MyString$ROT13
```

But if we wanted to parameterise these things, as per #183, how would you do that with the short-hand? Or does that mean we'd need both short and long-hand?

```
baz MyString$ROT13(10, "blip", false)
```

If that makes you cringe, maybe we should avoid short-hand for now because it's so hard to extend.

**Comment by warpfork** [comment]
To the very end bit: I'd say the longhand is always necessary, yeah.  Inline parameterization would get nuts, fast.

I'd imagine:

```
advanced Rot13 {
    alg "RotN"
    param amount 13
}

advanced Rot14 {
    alg "RotN"
    param amount 14
}

type FooString string representation advanced Rot13
type BarString string representation advanced Rot14

type BazStruct struct {
    foo FooString
    waz String<Rot14> # ... see comment below, though
}
```

This leaves us with a fairly high "setup cost" of declaring the `advanced` blocks, but it's at least certainly consistent and predictable in structure.  I'd actually ditch allowing full blocks directly following the representation clause on a type declaration.  It seems valuable to me to be able to skim down the left-hand side of a file and see the word (or lack of the word) "advanced" when reading a schema, and prepare myself accordingly.

That last bit -- the `BazStruct.waz` field -- is... questionable.  When I first started tossing these syntaxes around, it was mostly with the target of maps and lists.  *Those have a syntax for anonymous declarations* -- strings and bytes *don't*.  So fitting any inline syntax to strings and bytes would need to struggle with the propriety of sticking a marker on the end of an existing named type.  Maybe that's fine.  I'm not sure.

(And I notice I've already fallen back to `<>` because `$` just reads as line-noise, compiler-munging, or PHP to me, apparently.  But that was more instinctive than an intentful comment here.)

**Comment by vmx** [comment]
I'm not sure I got the full picture. But the longhand version reads good to me and I wouldn't do a shorthand version for now. I'd expect that a shorthand version would naturally emerge (if needed) once there's more schemas out there.

**Comment by rvagg** [comment]
OK, I dig those examples @warpfork (except for `waz String<Rot14>`). I was pushing parameterisation back a step but I can see how it makes sense this way and could still be quite useful.

On a `<>` tangent, I could imagine some future iteration of schemas introducing templating C++ style, or generics Java style:

```
type <X, Y> FooTmpl struct {
  key X
  secret Y
}

type StrByteFoo FooTmpl<String, Bytes>
type ByteByteFoo FooTmpl<Bytes, Bytes>
```

The primary objection being that such complexity causes cognitive maintenance burden that explicitness and verbosity avoids. But still, it's how my mind thinks `<>` should work and I'm certain I'm not alone; and unleashing `<>` that doesn't do this kind of thing is going to require more explanation than it should.

**Comment by rvagg** [comment]
Most basic example:

```
advanced Rot13 {
  algorithm "IPLD/ROT13"
}

type FooString string representation advanced Rot13

type BazStruct struct {
  foo FooString
  bar Int
}
```

**Comment by rvagg** [comment]
```
advanced Rot13

type FooString string representation advanced Rot13

type BazStruct struct {
  foo FooString
  bar Int
}
```

**Comment by warpfork** [comment]
Recap on most-distilled concerns:

- as long as there's an 'advanced' keyword showing up on the left side of the file
- and there's a clear discriminator in mapping them onto a type (to keep them distinct from built-in representations)

... then I'm good.

Couple things I'm lukewarm on or would be willing to bet we'll revisit:

- I'll be surprised if we don't end up with a block after the '^advanced' declaration.  Not unpleasantly; just would bet a nickel against.
- Unsure about trying to avoid the 'algorithm' reference.  It's a choice of where to point a jointable: either on that string, or on the must-be-locally-unique identifer following the 'advanced' keyword.  Either is viable, but loading the semantic join onto a must-be-locally-unique identifier seems more likely more problem-prone to me.

... but neither of these are blocking concerns.  And if we're all agreed that the '^advanced' declaration exists at all, then even expanding it to include a block later is a pretty minimal stretch and wouldn't trigger a cascading rethink of our other syntax choices.

And also, yeah, I'll give up on `<>`.

**Comment by rvagg** [comment]
moving this back to #182 after having agreed together on that last version of the syntax above (for now!)
