### ISSUE TITLE
Needs tl;dr

### ISSUE THREAD

**Issue by fulldecent** [ipld/specs#224]
Here's some URIs:

about:blank
https://google.com
data:image/png;base64,iVBORw0KGgoAAA
ANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4
//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU
5ErkJggg==

Please provide some examples upfront at https://ipld.io and at the top of the specification.

I am trying to learn more, am several pages into the project and I still don't know what an IPLD looks like.

**Comment by rvagg** [comment]
https://github.com/ipld/ipld/issues/81#issuecomment-564713087

> Ya, the website is not very informative. We’re going to fix it in 2020 but we’re a little busy right now just improving the libraries and the docs. Having a better website that then points you to bad or missing docs and difficult to use libraries didn’t seem like a good prioritization of our time here at the end of the year.
>
> If you’re interested, we do have great docs for IPLD Schemas now ;) https://specs.ipld.io/

We're aware of the poor state of documentation about the basics of IPLD and are keen to sort it out, we'll get there soon!
