### ISSUE TITLE
README and web site needs explanation what IPLD stands for

### ISSUE THREAD

**Issue by galets** [ipld/specs#226]
Web site and surface documentation do not make it clear what IPLD actually stands for. In order to clear up some confusion newcomers might have, README.md must me updated with a paragraph stating "IPLD stands for Inter Planetary Lxxxxx Dxxxxx". Without such notice the visitors would spend mental cycles trying to guess what is this L.D. instead of evaluating the project merits

**Comment by rvagg** [comment]
"InterPlanetary Linked Data" is what it stands for fwiw.

I just did a scan of the introductory docs on IPFS and notice they don't even try to expand the acronym, it's really not that helpful unless you want to get into the acronym being a vision for the expansive potential of the technology.

I think this is going to have to be something we cover on the new website that we're going to try and prioritise during this new year. We're keenly aware that we don't have very good on-ramps to any of this stuff but are slowly chipping away at it, see https://specs.ipld.io/schemas/ for an example of some of our newer work and our attempts to make it approachable.
