### ISSUE TITLE
Add motivation section

### ISSUE THREAD

**Issue by fulldecent** [ipld/specs#231]
Please add a motivation section that answers this existential question:

> A standard for content-addressed, authenticated, immutable data structures already exists and is implemented on billions of devices (RFC 3986). What additional problems are in-scope for this new standard?

**Comment by rvagg** [comment]
https://github.com/ipld/specs/blob/master/FOUNDATIONS.md should have most of that type of thing.

URIs don't address immutable data by default and the content and the URI don't necessarily have a direct relationship. i.e. RFC 3986 supports none of these by itself : _content-addressed, authenticated, immutable data_

IPLD is for data that's more like Git than web content with human-readable addressing. Content addressing means that the address has a direct relationship to the content and if the content changed then the address would necessarily need to change.

**Comment by fulldecent** [comment]
URIs *do* address immutable data. Following are just some of the IETF standards and drafts which conform to the URI specification and seem to cover the entire scope of this IPLD project.

https://tools.ietf.org/html/rfc6920

https://tools.ietf.org/id/draft-farrell-ni-00.xml 

https://tools.ietf.org/html/draft-shi-p2psip-hier-arch-00

https://tools.ietf.org/html/draft-farrell-decade-ni-06
