### ISSUE TITLE
Designing IPLD Selectors

### ISSUE THREAD

**Issue by nicola** [ipld/specs#35]
# IPLD Selector Plan

It has been quite a long time of exciting conversations about IPLD Selectors, in this document we try and look to understand how we can do them and what we need. Pleas post here your use cases

### Design goals

The IPLD selector is a simple language to select subgraph of an IPLD object.
Similarly, CSS selectors select a subtree of the HTML DOM tree to apply some style, Unix globs selects a subtree of folders and files in a file system.

The IPLD Selector **must** be:
- **simple**: a very simple language
- **cheap**: should have a very small runtime (otherwise IPLD selectors can be used to overload nodes in the network)
- **provable**: every subtree should be presented with a proof (unless the request is performed locally and the computer is trusted)

The IPLD Selector **should** be:
- **path-compatible**: the selector language should be compatible with the unix-path, this would allow us to reuse the way we address content for this purpose

The IPLD Selector **must not** be:
- **full-query**: a complex query language that performs transformation of the graph (SUM, JOIN)
- **high-complexity**: beyond regular language

## Use cases

Here is a list of use cases that I collected with different members of the community, I would love for @wanderer to input his own here too.

1. **Pointing**: Getting known nodes
   1. Root node (trivial)
    It can be done via the current path scheme `/ipld/hash/`
   2. Leaf node with known path (trivial)
    It can be done via the current path scheme `/ipld/hash/node`
2. **Selecting**: Getting unknown nodes
   1. One subgraph
      1. expand attribute's children
      - Glob: `/ipld/hash/attribute/*/`
      - CSS: `#hash > .attribute > *`
      2. expand the entire graph
      - Glob: `/ipld/hash/attribute/**/*`
      - CSS: `#hash > .attribute *`
   2. Multiple subgraphs
      1. with known properties
       Glob: `/ipld/hash/{attribute1,attribute2}`
       CSS: `#hash > .attribute1, #hash .attribute2`
3. **Filtering**: Get known attributes of unknown nodes
   1. find matching property in attribute's children
     Glob: `/ipld/hash/attribute/*/property`
     CSS: `#hash > .attribute > * > .property`
   2. find matching property in the entire graph
     Glob: `/ipld/hash/attribute/**/property`
     CSS: `#hash > .attribute .property`
   3. find graph of a matching property
     Glob: `/ipld/hash/attribute/**/property/**`
     CSS: `#hash > .attribute .property *`
   4. filter by regex on property
     Glob: `/ipld/hash/attribute[0-9]/name`
     CSS: `#hash > .attribute[id^='s']` *(actually not the same!!)*
4. **Filtering/Searching**: Get known relations of attributes
   1. find all the nodes that have attribute1 and parent references to it with attribute2
     Glob: cannot use kleene property across folder
     Regex: `/ipld/hash/(.*)/((attribute1/attribute2)/)*`
     CSS: `#hash .attribute1 > .attribute2`

#### Get the name of all of my friends
```
root: {
  friends: [h1, h2, h3]
}
h1: {
  name: "Juan",
  ..
}
h2: {
  name: "Jeremy",
  ..
}
h3: {
  name: "David",
  ..
}
```

```
// Raw tree: tree filled with missing pieces
// Can be streamed but only as patches (will explain more)
f(root) == {
  friends: [{name: Juan}, {name: Jeremy}, {name: David}]
}

// Transformed tree: only return the selected elements
// Can be streamed
f_transformed(root) == ["Juan", "Jeremy", "David"]
```

- Glob: `/ipld/root/friends/*/name`
- CSS: `#root > .friends > .name`

#### Get every block in a sharded data structure

```
root: {
  filename.txt: {
    shards: {
      shard1: [h1, h2],
      shard2: [h3, h4]
    }
  }
}

h1: XXX
h2: YYY
h3: ZZZ
h4: 000
```

```
f(root) == {
  filename.txt: {
    shards: {
      shard1: [XXX, YYY]
    },
    shards: {
      shard1: [ZZZ, 000]
    }
  }
}
f_transformed(root) == [XXX, YYY, ZZZ, 000]
```

- Glob:
  - `/ipld/root/filename.txt/shards/shard[0-9]/*` (or similar)
  - `/ipld/root/filename.txt/shards/**/*` (if guaranteed to only have shards)
- CSS:
  - `#root > filename.txt > .shards > * > hash` (assuming that hash is a type)
  - `#root > filename.txt > .shards > * > *`
  - `#root > filename.txt .shards` * (if guaranteed to only have shards)

#### Get blockchain's entire block headers (@whyrusleeping need)

```
root: {
  parent: p1,
  block: b1
}
p1: {
  parent: p2,
  block: b2
}
p2: {
  parent: genesis,
  block: b3
}
genesis: {
  parent: null,
  block: b4
}
```

```
f_transformed(root) == [
  {parent: p2, block: b2 },
  {parent: genesis, block: b3 },
  {parent: null, block: b4 }
]
```

- CSS: `#root .parent > .parent` (actually this does not guarantee it, but works in this case)
- Glob: `/ipld/(parent/)*` (this does not work in practice)

## Existing work

- JSON Path
- XPATH
- [JSON Select](https://web.archive.org/web/20160511140902/http://jsonselect.org/#tryit)
- [t-regex](http://nlp.stanford.edu/software/tregex.shtml)

## Temporary conclusion

I am experimenting with different already existing selectors, I believe that if we want to make our selector language simple, it would be an advantage if it is a selector many are already comfortable with (like in my examples Globbing or CSS selectors).

I have a strong preference for re-purposing globbing for IPLD, since globbing is unix-friendly, meaning that we can use the way we use globbing in the unix shell to select subgraphs in IPLD - hence might be backwards compatible with existing systems

---

I need use cases! @whyrusleeping, @diasdavid, @dignifiedquire, @wanderer, @jbenet

**Comment by wanderer** [comment]
The usecases that I have are simple globbing. requesting `accounts/<account_address>/*` and getting back the entire subtree would be nice. 

I'm not sure if selectors should be implemented at the file system level. Glob itself is just a userspace program. Would there be any good ways to implement selectors as userspace apps here?

**Comment by nicola** [comment]
My proposal is to be aligned with the transformation world we discussed previously:
- **/select/hash**/path/towhatherver

**Comment by dignifiedquire** [comment]
I want to warn against using globbing. I have seen quite a few cases where globs where not sufficient to select nested objects and fear that this will happen here as well. So something in the direction of CSS selectors seems to be more viable to me.

**Comment by nicola** [comment]
@dignifiedquire have a look at extended globbing

**Comment by nicola** [comment]
I have been running some experiments here: https://github.com/nicola/js-ipld-selector
Right now I am just exploding all the possible tree, listing all the paths and match them and return the matched ones. It would be best to implement an efficient way to explore the graph and abandon the unneeded branches (there must be some already defined strategy for this (it feels like existential and universal identifiers!))

**Comment by danfinlay** [comment]
An interesting use case from the world of Ethereum:

When loading a web interface to an ethereum application, the page will generally load many pieces of state from a single smart contract, which is computed from a specific branch of the Ethereum state trie.

A particularly read-intensive example of an Ethereum application (that would ideally be fast to load) is a decentralized marketplace:
https://mkr.market/#trade/W-ETH/DAI

This site is very popular, despite loading quite slowly!  It loads slowly because right now the client has to request each individual piece of data from the server.  If we were able to cache clusters of the state trie on the client, and simulate these transactions locally, we could speed this up dramatically.

**Comment by rvagg** [comment]
Closing due to staleness as per team agreement to clean up the issue tracker a bit (https://github.com/ipld/team-mgmt/pull/28). This doesn't mean this issue is off the table entirely, it's just not on the current active stack but may be revisited in the near future. If you feel there is something pertinent here, please speak up, reopen, or open a new issue. [/boilerplate]
