### ISSUE TITLE
Handle IPLD changes proposed by @davidar and @mildred

### ISSUE THREAD

**Issue by daviddias** [ipld/specs#39]
There is a long made PR by @davidar in ipfs/specs that was never handled and now the IPLD specs live here. @nicola could you make sure to review the proposed changes and incorporate whatever is needed in the IPLD spec?

Link to the PR - https://github.com/ipfs/specs/pull/111

**Comment by daviddias** [comment]
Another one, made by @mildred, related with this -- https://github.com/ipfs/specs/pull/116

**Comment by Stebalien** [comment]
Random note: we should probably use `/` instead of `$` as our special character as it's usually reserved for paths. That is, `{'/multibase': "...."}`.
