### ISSUE TITLE
Selectors: Use cases (from Q3 Workshop)

### ISSUE THREAD

**Issue by nicola** [ipld/specs#4]
Use cases:
1. Getting a root node
2. Path of single nodes (chain from root)
3. Look up in a trie (sharding, route planning)
4. Ranges on an array (section out of a video)
5. Predecessor/Successor Query (binary search)
6. Merkle B-Tree (select a key, peergos)
7. Prefetch on a VM/Container
8. Version range selection

Properties:
- Provable/Authenticated
- No assumption about data store
- Graph is immutable 
- (coubl be) URI-friendly

---

cc @jbenet, @mikolalysenko, @dignifiedquire, @daviddias, @chriscool, @John-Steidley

**Comment by chriscool** [comment]
Maybe this is an example of "1. Getting a root node" (taken from `ipfs object put --help`):

```
$ cat <<EOF | ipfs object put
      {
          "Data": "another",
          "Links": [ {
              "Name": "some link",
              "Hash": "QmXg9Pp2ytZ14xgmQjYEiHjVjMFXzCVVEcRTWJBmLgR39V",
              "Size": 8
          } ]
      }
added QmZZmY4KCu9r3e7M2Pcn46Fc5qbn6NpzaAGaYb22kbfTqm
$ ipfs object get QmZZmY4KCu9r3e7M2Pcn46Fc5qbn6NpzaAGaYb22kbfTqm
{"Links":[{"Name":"some link","Hash":"QmXg9Pp2ytZ14xgmQjYEiHjVjMFXzCVVEcRTWJBmLgR39V","Size":8}],"Data":"another"}
```

**Comment by dignifiedquire** [comment]
@nicola is this the latest issue, or is there another more up to date?

**Comment by nicola** [comment]
@dignifiedquire we haven't discussed this beyond labweek!

**Comment by dignifiedquire** [comment]
@nicola we should start looking into this, now that the baseline for IPLD is getting more solid :)

**Comment by daviddias** [comment]
🙏 @nicola

**Comment by ghost** [comment]
Use case: full text search, faceted search

**Comment by rvagg** [comment]
Closing due to staleness as per team agreement to clean up the issue tracker a bit (https://github.com/ipld/team-mgmt/pull/28). This doesn't mean this issue is off the table entirely, it's just not on the current active stack but may be revisited in the near future. If you feel there is something pertinent here, please speak up, reopen, or open a new issue. [/boilerplate]
