### ISSUE TITLE
Lowercasing filenames

### ISSUE THREAD

**Issue by vmx** [ipld/specs#81]
If you're on a terminal, it's easier to work with lowercase file names. Are there any objections to make all the spec filenames and directories lowercase?

**Comment by Stebalien** [comment]
Meh? We already have upper-case README, LICENSE, etc. I'm not sure it's worth it.

**Comment by vmx** [comment]
I guess those are all uppercase for history reasons. To me they are kind of "meta files", hence I'd lowercase the other ones for distinction (especially directories I might to cd into).

**Comment by mikeal** [comment]
I don't have a strong opinion either way.
