### ISSUE TITLE
Selector Verify Interface

### ISSUE THREAD

**Issue by Stebalien** [ipld/specs#90]
I'm thinking something like:

```go
type Verifier interface {
	// Expects returns the next expected CID and a boolean indicating if we *are* expecting a CID.
	Expects() (cid.Cid, bool)
	// Receive a block, advancing the selector.
	Receive(Block) error
	// Skip the block.
	Skip() error
}
```

As we receive messages via graphsync, we'd (in graphsync):

1. For every response in the message.
  a. If the response is "I don't have", call `Skip` on the verifier.
  b. If the response is content, partial content, etc., while `verifier.Expects()` is in the set of blocks in the message, keep feeding those blocks into `verifier.Receive()`.

This shouldn't require any additional information.

cc @hannahhoward, @warpfork, @vmx, @mikeal.

**Comment by hannahhoward** [comment]
As I look at this, it makes sense to me provided we can assume traversing a selector is deterministic, based on the the selector and content being traversed, even if parts of the content are missing.

Essentially, for a selector A, when applied to a DAG of nodes B, the order I will visit nodes to apply selector A will always be the same. This will be true even if I have to skip some nodes in DAG B cause I don't have them (or the remote does not have them).

If this is the case I only envision two components sent over the wire:
1. A block
2. A CID that is part of the traversal that the remote did not have

Of course, the verifier struct @Stebalien implies that Receive gets blocks that don't necessarily match the selector but part of the traversal. (Or are necessary to verify a sub branch does not match the traversal)

So I'd like to make a slightly modified proposal:

Overall call signature:

```go
func VerifySelection(root CID, selector Selector, visit VisitFn) chan Node 
```

returns a channel of verified, matching Nodes

and the VisitFn looking like this:

```go
 type VisitFn func(visitor VerifyVisitor) {
}
```

and the VerifyVisitor {

```go
type VerifyVisitor interface {
  Cid() cid.Cid
  Receive(Node) error
  Skip() error
}
```

Essentially the visit functions job is to call receive or skip, letting the traversal continue based of the selector being applied client-side.

**Comment by hannahhoward** [comment]
^^ @Stebalien  @warpfork  @vmx @mikeal

**Comment by hannahhoward** [comment]
The visitFn would be supplied by go-graphsync and would essentially block until it got a response from the server regarding the given CID of whether it had it or not.

**Comment by Stebalien** [comment]
> Of course, the verifier struct @Stebalien implies that Receive gets blocks that don't necessarily match the selector but part of the traversal. (Or are necessary to verify a sub branch does not match the traversal)

As far as I'm concerned, a selector always selects a single connected sub-graph. Basically, the result of a selector is a trace of the traversal.

---

So, there *is* a tricky case here: repeated sub-dags. That is, we may want some way to tell the remote side "I already sent you that." That or maybe some kind of "I'm skipping forward N blocks, you should already have them.". I'm not sure...

**Comment by hannahhoward** [comment]
Yea but there is also the paths that need to be followed in order to get to the matching blocks, or to prove there are no matching blocks.

IOW, If I'm selecting CID + /parent/parent/parent

I need to send the node itself, the node's parent, the node's parent's parent, and the node's parent's parent's parents -- in order to verify that the only actually "matching block" from the requestor's standpoint -- i.e. the node's parent's parent's parent -- is in fact valid.

I'm saying Go-Filecoin or whomever is making the selection only cares the great grandparent node -- that's actually the only thing that matches the selector, but to verify it the whole traversal must be made.

**Comment by hannahhoward** [comment]
I apologize I see that IPLD Selectors in the spec do always describe a subset of a graph with a path back to the root.

However, there are also cases where you clearly need nodes in a graph that are not in the result to verify results.

for example, if I have a glob selector with a filter level search -- i.e. CID + /a/?abc I need all of the children of A to verify which ones match ?abc .

**Comment by hannahhoward** [comment]
Admitted this is not the first kind of selector we are implementing.

**Comment by hannahhoward** [comment]
Sorry, rewind, I believe the case for sending blocks that don't match is the fact that paths can exist within a block -- or so it appears based on the [IPLD path spec](https://github.com/ipld/specs/blob/master/IPLD-Path.md). So I cannot always determine purely from looking at the links on a block whether the blocks at those CIDs will match the selector without retrieving the blocks themselves. I think.

Sorry I am super out of my depth here. I'm just supposed to implement the wire protocol! @warpfork please help.

**Comment by warpfork** [comment]
> So I cannot always determine purely from looking at the links on a block whether the blocks at those CIDs will match the selector without retrieving the blocks themselves. I think.

I think too.

Say we've got these objects:

```
bafyblwkrgj//foo="asdf"
bafyblwkrgj//parents/0=Link("bafywoelkfj")
bafyblwkrgj//parents/1=Link("bafyfoffle")

bafywoelkfj//matches="yes"

bafyfoffle//doesntmatch="value is irrelevant to example"
```

and we run a selection starting at `bafyblwkrgj` and matching `parents/*/matches`.

What do we return?

- `parents/0/matches` is a path that matches.  We could see that after loading the `bafywoelkfj` block; and we'll definitely send the `bafywoelkfj` block for graphsync responses.
- `parents/1/matches` is a path that doesn't obviously *not* match until you've loaded the `bafyfoffle` block.

So, if this is just a selection we were running locally, and we trust the other code in our same process on the same machine, fine; whatever callback the caller provided, we can just call it with precisely the Node and Path that matches; easy, done.

If we're producing the stream of blocks to send to graphsync and a remote verifier... it would seem that unless that remote verifier trusts us regarding nonmatches, we probably need to send them the `bafyfoffle` block, just so they can ignore it (but confidently).

It's possible that the state machines on both sides of this process could be implemented without extra control messages to mark things like these blocks which we're including despite not matching.  I'm uncommitted to whether or not that's a *good* idea even if it's *possible* -- this seems like a situation where a little more  contextualization information might be extremely useful for development and debugging, sanity checks, meaningful error reports, and future proofing.

**Comment by vmx** [comment]
> The visitFn would be supplied by go-graphsync and would essentially block until it got a response from the server regarding the given CID of whether it had it or not.

I wouldn't block anything. I would keep going and if it turns out it doesn't verify the caller would terminate the connection and disregard the blocks it already received.

**Comment by hannahhoward** [comment]
Supplanted by additional discussions of go-ipld-prime
